### PR TITLE
Unregister the shortcut before we call register if it's already registered

### LINKED ISSUE #3: Fails to register after plugins are installed
When I edit `plugins` section in hyperterm config, then I get "Failed to register" dialog after they reload (after npm install).

I suspect you somehow forget to unregister global shortcut before registering it again. Could you try modifying `register` function so it detects whether it registered global plugin before and try to unregister it first? (instead of doing it in `subscribe`).

### PR DESCRIPTION
**Pull request by soutar**
I think this fixes #3 - @sheerun how does this look to you?

### CODE REVIEW

**Comment by sheerun** [comment]
I think it won't work if someone changes the accelerator (e.g. it was F12 but it is now F11).

You probably need to save previous accelerator and unregister on it.

**Comment by soutar** [comment]
@sheerun I think this should work fine just for making sure a shortcut isn't already registered when we call `globalShortcut.register`. We deal with the general accelerator changing scenario here https://github.com/soutar/hyperterm-summon/blob/master/index.js#L50-L54.

Changing accelerators still works and I'm not seeing the error dialog after plugins reload so I'm tempted to just merge.

**Comment by sheerun** [comment]
OK, so let's merge and I'll test it one more time after you release.

**Comment by soutar** [comment]
@sheerun It's up on npm as v1.2.2 but it seems busted. I think you were right! I'll get a new PR up ASAP

**Pull request merged**
