### PR TITLE
w.i.p. : Hide on start

### PR DESCRIPTION
**Pull request by mwoz123**

### CODE REVIEW

**Comment by dcalhoun** [comment]
Thanks for the PR, @mwoz123. I'll do my best to find time to review and provide feedback.

**Comment by mwoz123** [comment]
@dcalhoun - did you had a chance to take at it? any hints ?

**Comment by dcalhoun** [comment]
Hey @mwoz123. 👋🏻 Unfortunately, I have not found time to explore this. It is bit of a busy time for me, personally. This still remains on my list of things to review. Thanks for your patience. 🙇🏻

**Review by dcalhoun — COMMENTED** [review]
Hey @mwoz123. 👋🏻 

I spent some time exploring these changes and possible alternatives. Unfortunately, I was unsuccessful in finding a path to accomplishing https://github.com/soutar/hyperterm-summon/issues/77. 

The changes in this PR do not appear to succeed, as you mentioned. Also, I was unable to find an event/hook within [Hyper's Extension API](https://hyper.is/#extensions-api) or [Electron's `app` events](https://www.electronjs.org/docs/latest/api/app) that triggered consistently after the app and initial window finish rendering. 

I am closing this PR, but please feel free to continue exploring. I welcome a PR that is functioning if you identify an approach that works. However, I do not plan to continue exploring this myself.

**Comment by mwoz123** [comment]
> Also, I was unable to find an event/hook within [Hyper's Extension API](https://hyper.is/#extensions-api) or [Electron's app events](https://www.electronjs.org/docs/latest/api/app) that triggered consistently after the app and initial window finish rendering.

IMHO from the [docs](https://hyper.is/#extensions-api) `onApp` or `onWindow` 

METHOD | INVOKED FROM | DESCRIPTION
-- | -- | --
onApp | Electron | Invoked when the app first loads. If a plugin reloads, it's invoked again with the existing app.Parameters: app - The electron app. 
onWindow | Electron | Invoked when each window is created. If a plugin reloads, it's invoked again with the existing windows.Parameters: window - An electron BrowserWindow.

seems to be perfect candicates for it.

Not sure why it doesn't work ? :(

Could you just confirm that the 
`hideWindows(app)` is the right way to make the app hidden ?

**Comment by dcalhoun** [comment]
👋🏻 @mwoz123. Yes, I agree it seems like `onApp` and `onWindow` would be the appropriate location. Based on re-reading my own last comment, I was unable to successfully use those methods. 



> Could you just confirm that the
> `hideWindows(app)` is the right way to make the app hidden ?

Yes, [`hideWindows(app)`](https://github.com/soutar/hyperterm-summon/blob/616344491599351b6bdc228d1a6dacac9494a552/modules/windows.js#L18-L40) is the method for hiding all app windows.

**Pull request closed without merging**
